// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-enable-copy-shortcut'
  | 'prefs-title'
  | 'zoteroclaw-chat-section-header'
  | 'zoteroclaw-chat-section-refresh-tooltip'
  | 'zoteroclaw-chat-section-sidenav-tooltip';
